### ISSUE TITLE
Another gem

### ISSUE THREAD

**Issue by nviennot** [katafrakt/carrierwave-nobrainer#1]
Hi Paweł,

I didn't see you gem at first, but I made an adapter for carrierwave that is compatible with their latest version from master (to enable stuff like array of files with `mount_uploaders`).

You can check it out here: https://github.com/nviennot/carrierwave-nobrainer

Any chances you can replace the carrierwave-nobrainer gem with the new code?

**Comment by katafrakt** [comment]
Hi Nicolas,

I looked through your code and arrays of files look great. However, before getting your code I have few points I'd like to discuss.
- Your implementation seems to have problems with destroying models. The result is:

```
     Failure/Error: Model.first.destroy
     RuntimeError:
       can't modify frozen instance of ActiveSupport::HashWithIndifferentAccess
     # kernel/common/hash.rb:191:in `regular_writer ([]=)'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/activesupport-4.2.1/lib/active_support/hash_with_indifferent_access.rb:97:in `[]='
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/nobrainer-0.24.0/lib/no_brainer/document/attributes.rb:36:in `_write_attribute'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/nobrainer-0.24.0/lib/no_brainer/document/dirty.rb:73:in `_write_attribute'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/nobrainer-0.24.0/lib/no_brainer/document/missing_attributes.rb:54:in `_write_attribute'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/nobrainer-0.24.0/lib/no_brainer/document/atomic_ops.rb:187:in `write_uploader (_write_attribute)'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/bundler/gems/carrierwave-d7b18dd002cc/lib/carrierwave/mount.rb:176:in `write_file_identifier'
     # ./lib/carrierwave-nobrainer.rb:91:in `remove_file!'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `make_lambda'
     # kernel/bootstrap/proc.rb:20:in `call'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:228:in `halting_and_conditional'
     # kernel/bootstrap/proc.rb:20:in `call'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `call'
     # kernel/bootstrap/array.rb:76:in `each'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `call'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_destroy_callbacks'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /home/katafrakt/.rbenv/versions/rbx-2.5.4/gems/gems/nobrainer-0.24.0/lib/no_brainer/document/callbacks.rb:28:in `destroy'
     # ./spec/carrierwave_spec.rb:24:in `__script__'
     # kernel/common/eval.rb:101:in `instance_exec'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/common/kernel.rb:498:in `load'
     # kernel/delta/code_loader.rb:66:in `load_script'
     # kernel/delta/code_loader.rb:152:in `load_script'
     # kernel/loader.rb:656:in `script'
     # kernel/loader.rb:810:in `main'
```

To me it looks like carrierwave's error, which leads to my next point.
- Relying on gem version from master is risky and not quite production-friendly ;) I might add it as some development branch and wait for carrierwave to become stable.
- I'm not really sure about including carrierwave integration to every NoBrainer model just with adding a gem to Gemfile. I know this happens often in ActiveRecord's Rails world but I believe NoBrainer can do better and explicit inclusion of dependencies seems to become preferred in Ruby world lately.

Let me know what you think.

**Comment by nviennot** [comment]
I've fixed the destroy issue: https://github.com/nviennot/carrierwave-nobrainer/commit/b0f0709d40bc22f0e9a8dc17d71c9bfc0c5362ed

I was trying to match the https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb implementation.

It might be risky, but the other version is from +12 months ago. This is a long time :)

For the automatic integration, this what carrierwave behaves with other ORM, so I'd rather stick to their API. It's not really a big deal, it adds 5 methods to the model. It's like devise that adds its stuff to all models. I'm not too happy about it, but I think it's okay. Do you feel strongly about this?

**Comment by katafrakt** [comment]
I put my proposal into separate branch: https://github.com/katafrakt/carrierwave-nobrainer/tree/develop I'll merge it if it's okay with you.

I still decided to go with explicit include. This comes from my experience with fairly large systems, where methods came out from nowhere, which was a hell to debug, and also from Adam Hawkins's post about Ruby community: http://hawkins.io/2015/05/the-ruby-community-the-next-version/ I also feel that explicit is better than implicit and this is where we, as a community, should steer. Lotus, for example, is also built that way.

**Comment by nviennot** [comment]
Yeah, I'm good with the merge.

I've issued a fix for the `:filename => 'static.png'` feature: https://github.com/nviennot/carrierwave-nobrainer/commit/7e3d19885a3c5c474fade66d78f2639027f67ddd
It's running in a production system running fog/s3, and it seems fine on local disk as well.
With that fix in, it's good to go :)

The auto include is the least of my concern, it's okay if you require the user to be explicit. He can always `NoBrainer::Document.send(:include, CarrierWave)` in the initializer to get the automatic include :)

In terms of debugging, etc, the biggest problem is CarrierWave API IMHO: The file accessors override the original DB field accessors. Lots of code is weird because of that.

**Comment by katafrakt** [comment]
I have included your latest changes (and also had to make some fixes regarding inheritance, see: https://github.com/katafrakt/carrierwave-nobrainer/commit/9b2933128d0cb543bf9680b76015da4447c440c3). I also merged `develop` branch into `master`.

I'd be happy to add you as a collaborator to this repo, if you like.

**Comment by nviennot** [comment]
That would be great!

I'm also trying to push a few fixes in carrierwave. First three in: https://github.com/carrierwaveuploader/carrierwave/pulls/

**Comment by zedtux** [comment]
7 years later, I'm maintaining the nobrainer ORM gems including the nviennot's version.

As you don't seem to update this gem since years, would you consider to delete your gem from rubygems.org allowing me to push our official version of this gem please ? Or transferring the ownership on rubygems.org (which is quicker) ?

**Comment by katafrakt** [comment]
@zedtux sure, I can transfer the ownership. I guess your username on rubygems is the same?

**Comment by nviennot** [comment]
Guillaume is the MVP. Thank you Guillaume ♥️

**Comment by zedtux** [comment]
> @zedtux sure, I can transfer the ownership. I guess your username on rubygems is the same?

Yes it is !

**Comment by zedtux** [comment]
Thank you very much @katafrakt, I accepted the ownership. 👍
