### ISSUE TITLE
r.expr can't handle UploaderClass

### ISSUE THREAD

**Issue by niv** [katafrakt/carrierwave-nobrainer#2]
Hi,

using the latest nobrainer release (0.31.0) and your instructions in the README, I can't seem to assign uploaded images to any model.

It looks like the class is passed on straight through, instead of being transformed into a filename(?). This results in nobrainer complaining it can't pass a XXUploader class into r.expr.

Any guidance?

Cheers.

**Comment by niv** [comment]
Was something on my end. Works now. (I had a weird filename method that seemed to have broken my setup. Sorry about the noise.)

**Comment by katafrakt** [comment]
@niv it's great to know that someone is using this gem anyway :wink:

**Comment by niv** [comment]
@katafrakt 👍
